language: ruby
git:
  depth: 3
  submodules_depth: 100
before_install:
   - git submodule update --init --remote --recursive
rvm:
  - 2.7.0
before_script:
  - cd *
  - bundle install
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
  - bundle exec rake db:schema:load
script:
  - bundle exec rspec
services:
  - postgresql
notifications:
  email: false
